### ISSUE TITLE
SkillSend of Packet

### ISSUE THREAD

**Issue by AndenCastillo** [CwanOcak/Gepard#3]
Since I Already got PacketHook its already working but when i send like this

if (len == 10)
	{
		SocketForUse = s;
		charSkill = buf;
		lenghtSkill = len;
		flagSkill = flags;
		send(SocketForUse, (char*)charSkill, lenghtSkill, flagSkill);
	}

All Skill of Job are Triggered not the specific skills that i use

**Comment by babbsgit** [comment]
The quick brown fox
