### ISSUE TITLE
Gepard3,0

### ISSUE THREAD

**Issue by sgsilva** [CwanOcak/Gepard#4]
i was compiled and work, genereate dll, but for gepard3.0 dont work!

**Comment by babbsgit** [comment]
The quick brown fox

**Comment by uragan1987** [comment]
@Optcall can you upload your gepard.dll / gepard_o.dll to project

**Comment by ggpaeg** [comment]
Is it working on Gepard 3.0?
Same problem here, dll compiled but the server dont connect.
